# Use a Node.js base image
FROM node:18-alpine as build

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm i sweetalert2

COPY . .

# Expose port (optional, adjust as needed)
EXPOSE 8081

# Start nginx
CMD ["npm", "run", "dev"]

